### ISSUE TITLE
Label with Variable

### ISSUE THREAD

**Issue by becmar39** [bartbutenaers/node-red-contrib-ui-multistate-switch#10]
It is not possible to assign an variable e.g. {{msg.label}} to the Label field to show dynamically Switch Labels

**Comment by hotNipi** [comment]
Let's see what @bartbutenaers says but for now I give for it the label "enhancement"

**Comment by bartbutenaers** [comment]
Hi @becmar39,

I can see an added value in dynamically setting the label, and there are multiple ways to do that:
1. Keep a fixed label on the config screen, which can simply be overwritten via an input message (msg.xxx).
2. Replace the fixed label on the config screen by a TypedInput, where the label can be a fixed string or a msg.xxx field.
3. Keep a fixed label on the config screen, but allow it to contain a [Mustache ](https://mustache.github.io/) expression,.  Similar to some other (core) Node-RED nodes.  This way it also possible to _**mix**_ a fixed text and a mustache expression, e.g. *"Fixed {{msg.label}}"*.

@hotNipi Not sure which way is the best ...

P.S. I don't develop at the moment due to a surgery, so you will have to wait some time ...

**Comment by hotNipi** [comment]
As there will probably be some kind of "override options by msg.xxx" functionality - I'd suggest to keep it straight and simple and not provide multiple ways to do same thing. 
Just needs to be settled what will be the options the user can change...

**Comment by becmar39** [comment]
Hi,
no Problem. I tried Option 3. I think it is the best way, beacause you already said: Its similar to some (core) Nodes.

**Comment by bartbutenaers** [comment]
We have now [announced](https://discourse.nodered.org/t/announce-node-red-contrib-ui-multistate-switch-1-2-0-beta/50464) the first beta of version ***1.2.0***, which contains the Mustache functionality (option 3).  I am going to close this issue, since the discussion will be continued on Discourse.
