### ISSUE TITLE
Input-output message

### ISSUE THREAD

**Issue by hilba** [bartbutenaers/node-red-contrib-ui-multistate-switch#3]
Nice node! 
When I change the switch state using an input message, the state changes as expected (GUI) but no output message is generated, indicating this now state. Is it possible to have an option for this within the node? I have a workaround but it is not handy when having a lot of multistate switches.
![workaround](https://user-images.githubusercontent.com/19634484/110083110-9004e500-7d8e-11eb-860d-b4356e9b7128.jpg)

**Comment by hotNipi** [comment]
The pass-through functionality is not currently available. It is quite complicated feature and actually does not always satisfy all the user needs. 
Messages can't just passed through as for example if you have response message also coming from device  after actual state changed in device, then there is infinite loop produced. 
It can be done in the way that passed messages don't change the state but the widget loses meaning then.   
Also there is approach that the mouse click does not change the state of the switch but it changes only with incoming payload but that is also bad, because of it confuses the user by not indicating the user action success anyhow.
That much about complexity of the feature.

But it is under discussion and maybe at some day it will be available in one or other form.

**Comment by eddee54455** [comment]
+1 ..... I would like to see this too...

**Comment by pgalbavy** [comment]
Also +1 - I am used to other dashboard nodes behaving in a passive/pass-thgrough way and this confused me until I read the code.

While you say it's compilcated, not that I quite see why - setting SendMsg to true would work? - perhaps a toggle, defaulting to "true" for law-of-least-astonishment for new users - that allows pass-through or not?

**Comment by bartbutenaers** [comment]
Hi @pgalbavy,
Indeed I also thought first that this would be a simple feature.  Until the discussions started about it on Discourse (e.g. [here](https://discourse.nodered.org/t/announce-node-red-contrib-ui-multistate-switch-v1-0-0/41047/23?u=bartbutenaers)).
I will start a new discussion about it soon, to agree on the functionality before we start implementing it.  But before I can do that, I first have to process a large backlog of other things...

**Comment by fromCologne** [comment]
+1

**Comment by bartbutenaers** [comment]
We have now [announced](https://discourse.nodered.org/t/announce-node-red-contrib-ui-multistate-switch-1-2-0-beta/50464) the first beta of version ***1.2.0***, which contains pass through functionality.  I am going to close this issue, since the discussion will be continued on Discourse.
