### ISSUE TITLE
Validate Switch "State"

### ISSUE THREAD

**Issue by Zodiac-69** [bartbutenaers/node-red-contrib-ui-multistate-switch#5]
Is it possible to include a option where the "State" can be set to reflect the output or the input, similar to a normal switch when pass through is disabled?
Can then use feedback to the input to validate the switch state.

**Comment by hotNipi** [comment]
If so, it will be part of the pass-through logic which is still under the discussion.

**Comment by bartbutenaers** [comment]
We have now [announced](https://discourse.nodered.org/t/announce-node-red-contrib-ui-multistate-switch-1-2-0-beta/50464) the first beta of version ***1.2.0***, which contains pass through functionality.  I am going to close this issue, since the discussion will be continued on Discourse.  If your use case cannot be solved by the logic in our new version, then please let us know.
